version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/thewatcher
    depends_on:
      - db
      - redis
    networks:
      - thewatcher_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - thewatcher_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: thewatcher
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - thewatcher_network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - thewatcher_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - thewatcher_network

networks:
  thewatcher_network:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
